server:
  port: 8001

spring:
  profiles:
    active: dev
  application:
    name: Eureka Server Center

---
spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka